### ISSUE TITLE
Sippy misses existing bugs for test failures

### ISSUE THREAD

**Issue by bgilbert** [openshift/sippy#128]
It appears Sippy sometimes fails to associate existing bugs with test failures.

## Example 1

In [this page](https://sippy.ci.openshift.org/?release=4.6#TopFailingTestsWithoutABug), Ctrl-F `kubelet terminates kube-apiserver gracefully`.  I used Sippy to file [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1886563), which was a duplicate of [this one](https://bugzilla.redhat.com/show_bug.cgi?id=1882750).  Sippy finds neither of them (and they don't show up when clicking through to the [search page](https://search.ci.openshift.org/?maxAge=168h&context=1&type=bug%2Bjunit&name=4.6&maxMatches=5&maxBytes=20971520&groupBy=job&search=%5C%5Bsig-api-machinery%5C%5D%5C%5BFeature%3AAPIServer%5C%5D%5C%5BLate%5C%5D+kubelet+terminates+kube-apiserver+gracefully) either).

Update: as of now, Sippy seems to have figured this out, but it hadn't figured it out half an hour ago when I wrote the above.  The search page still hasn't.

## Example 2

In [this page](https://sippy.ci.openshift.org/?release=4.6#TopFailingTestsWithoutABug), Ctrl-F `OpenShift APIs remain available`.  That failure [should](https://github.com/openshift/sippy/issues/23#issuecomment-655289547) link to [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1845411), but did not do so on the basis of [this comment](https://bugzilla.redhat.com/show_bug.cgi?id=1845411#c8) and continued not to do so when the test names were added to the Environment field.

**Comment by bparees** [comment]
for a given sippy release page (e.g. 4.6), sippy only attempts to match test failures to bugs that are targeted at that release.

In your 2nd example, you linked to the 4.6 release page, but the bugs you think it should have associated are targeted to 4.7.

The intent here is that if the team that owns the bug hasn't targeted a clone to the release where sippy is seeing the failures, it doesn't count.

**Comment by bgilbert** [comment]
The bug was reported against 4.6, so the test failure is known to the owning team, but Sippy is presenting it as though it's actionable.  What's the intended action for a build-watcher here?  File a duplicate bug?

**Comment by bgilbert** [comment]
Reported the search issue as https://github.com/openshift/ci-search/issues/92.

**Comment by bparees** [comment]
> What's the intended action for a build-watcher here? File a duplicate bug?

clone the bug back to the release where sippy is seeing the issue.  Because we want to ensure the team fixes the bug where we're seeing it, not just in some future release.  (or at least considers doing so)

**Comment by bgilbert** [comment]
> clone the bug back to the release where sippy is seeing the issue

You mean the bug that Sippy isn't displaying?

I understand your point, but the current UX creates unnecessary correlation work for build watchers.  If we want that clone operation to continue being a manual step, we could at least show a "related bugs" column in Sippy.

**Comment by bparees** [comment]
> You mean the bug that Sippy isn't displaying?

yes

> I understand your point, but the current UX creates unnecessary correlation work for build watchers. If we want that clone operation to continue being a manual step, we could at least show a "related bugs" column in Sippy.

sure, that's a great ux improvement
