### ISSUE TITLE
No data for release-4.6

### ISSUE THREAD

**Issue by alvaroaleman** [openshift/sippy#217]
It appears sippy has no data for relese-4.6 at all: https://sippy.ci.openshift.org/?release=4.6

<img width="1010" alt="empty-sippy" src="https://user-images.githubusercontent.com/6496100/111225987-e0fab180-85b6-11eb-8103-d193f9bb40e8.png">

**Comment by bparees** [comment]
thanks, there's a panic happening due to BZ processing, looking into it.
