### ISSUE TITLE
Adding OLM tests on sippy for analysis

### ISSUE THREAD

**Issue by Bowenislandsong** [openshift/sippy#28]
OLM would like to seek for support on investigating flaky tests with Sippy. I am not very familiar with the procedure on pushing tests onto k8s test grids, https://github.com/kubernetes/test-infra/issues/18237. Any help there is appreciated.

More importantly, OLM would like to use Sippy to analyze flaky tests. The current scope of Sippy seems to be centered around OCP tests present on the k8s test grid. I wonder if we could add support for other projects such as OLM, once pushed on to the test grid. 

If OLM can not qualify as part of the k8s test grid, is there any other suggestion to integrate with Sippy? Thank you.

**Comment by bparees** [comment]
any release informing or blocking jobs are eligible for testgrid, and sippy will automatically process any release blocking or informing job that's part of the testgrid dashboard.

see https://github.com/openshift/ci-tools/tree/master/cmd/testgrid-config-generator for documentation on how to get a job added to testgrid.
