### ISSUE TITLE
sippy reports test pass percentage 100% when the test has failures

### ISSUE THREAD

**Issue by bparees** [openshift/sippy#291]
https://sippy.ci.openshift.org/sippy-ng/tests/4.10?filters=%7B%22items%22%3A%5B%7B%22id%22%3A1%2C%22columnField%22%3A%22%22%2C%22operatorValue%22%3A%22%22%2C%22value%22%3A%22%22%7D%2C%7B%22id%22%3A99%2C%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22%20Prometheus%20when%20installed%20on%20the%20cluster%20shouldn%27t%20have%20failing%20rules%20evaluation%22%7D%5D%7D

reports 100% passing for the test:
![image](https://user-images.githubusercontent.com/4974046/134254856-b78a8be3-1494-407b-bdd2-c717ae94a70c.png)

but clicking on test failures shows that it has in fact failed some recently:
https://sippy.ci.openshift.org/sippy-ng/jobs/4.10/runs?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22failedTestNames%22%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22%5Bsig-instrumentation%5D%20Prometheus%20when%20installed%20on%20the%20cluster%20shouldn%27t%20have%20failing%20rules%20evaluation%20%5BSkipped%3ADisconnected%5D%20%5BSuite%3Aopenshift%2Fconformance%2Fparallel%5D%22%7D%5D%7D&sortField=timestamp&sort=desc

![image](https://user-images.githubusercontent.com/4974046/134254959-8728009c-7d57-4ec4-a7c3-5a5fbb7a1d59.png)

is this just a rounding issue or something more?

**Comment by stbenjam** [comment]
Yea, it was rounding -- this is how it'll look with my fix:

![image](https://user-images.githubusercontent.com/429763/134495076-4434c4c2-a8c1-4ea2-afdf-13347e805442.png)
