### ISSUE TITLE
infrequent jobs are not included in variant aggregation

### ISSUE THREAD

**Issue by bparees** [openshift/sippy#85]
current logic computing the variant aggregations is ignoring jobs categorized as "infrequent", they should be included (any cluster run on a given variant tells us something about our stability on the variant, and in some cases we only have infrequent jobs on the variant, though we may have multiple jobs that together add up to a useful volume of data).

**Comment by deads2k** [comment]
I see this as fixed in currently deployed level.

**Comment by bparees** [comment]
yeah, looks to be resolved, thanks
